### ISSUE TITLE
关于5ber无法写入新西兰esim

### ISSUE THREAD

**Issue by ZyaireXv** [liuran001/Roaming-SIM#11]
eid 为 890860 开头的 5ber.eSIM 和 eSIM.me 无法正常写入 One NZ 的 eSIM Profile
请问有没有大佬有解决方案

**Comment by liuran001** [comment]
这个似乎是固件问题，有极少数用户是可以正常写入的，但是绝大多数都无法成功写入

可能唯一的解决方案是使用 diy 卡或者 estk，而不是 5ber

**Comment by aran-w** [comment]
可以在 5ber App 里联系 5ber 客服，会提供给你一个二维码来下载一个 eSIM profile 用来“升级”卡的固件，据说升级之后就可以正常下载 One NZ 的 eSIM 了。不过我自己还没试过，正在和 One NZ 的客服扯皮试图让他们给我发个新码，不行就只能再买一张试试看了。

ref: https://www.nodeseek.com/post-67964-1
在这个论坛看到的方法

**Comment by liuran001** [comment]
现在5ber已经修复了此问题，并且支持在app中自助更新固件

（早就修复了，但是忘记回了）
