### ISSUE TITLE
Lycamobile UK is just 17kBytes

### ISSUE THREAD

**Issue by laf0rge** [liuran001/Roaming-SIM#37]
FYI: I just downloaded a Lycamobile UK eSIM profile, and it's only 17544 bytes in size, very far from the 58.8 kB you list on your wiki page.

**Comment by liuran001** [comment]
Are you using a phone with built-in eSIM functionality, or another plug-in eSIM chip such as eSTK.me?
Some of the contents in the table are tested in the plug-in 5ber.eSIM, due to some reasons, the size of the profile measured in 5ber.eSIM will be significantly larger than other chips.

**Comment by laf0rge** [comment]
I'm using sysmoEUICC1-C2G, which is a removable plastic card eUICC.

**Comment by liuran001** [comment]
I've just gone and asked someone else and it seems that because Lycamobile UK updated their carrier system, the config file downloaded before was indeed 58.8 kB in size!
I will change the form later, thanks for your feedback!

**Comment by laf0rge** [comment]
Technical background: The memory utilization of the fully installed profile is implementation dependent.  It differs based on how much overhead (and what kind of internal data structures) the CardOS on the eUICC uses.

So if you want to compare eSIM profile sizes in a meaningful way, you'd have to use the same eUICC for all of the profiles.  Or, alternatively, you could simply measure the size of the "boundProfilePackage" during the download process. It would be very easy to modify e.g. lpac (or any other open source LPA software) to dump/expose this information during download.

**Comment by liuran001** [comment]
> Technical background: The memory utilization of the fully installed profile is implementation dependent. It differs based on how much overhead (and what kind of internal data structures) the CardOS on the eUICC uses.
> 
> So if you want to compare eSIM profile sizes in a meaningful way, you'd have to use the same eUICC for all of the profiles. Or, alternatively, you could simply measure the size of the "boundProfilePackage" during the download process. It would be very easy to modify e.g. lpac (or any other open source LPA software) to dump/expose this information during download.

We had a plan to separate the size of the downloaded profiles for different chips a long time ago, but for many reasons this plan has been put on hold
Therefore, the data in this table is for reference only (at least for the time being)

If we get enough samples, we may try to improve this table.
